### ISSUE TITLE
Every update break OpenCV

### ISSUE THREAD

**Issue by warcanoid** [home-assistant/hassio-opencv#1]
I updated HA from 0.94.3 to 0.94.4 and something again deleted OpenCV library:No OpenCV library found! Install or compile for your system following instructions here: http://opencv.org/releases.html
Is this a bug? Delete library after each update? Opencv folder is still in config/!

**Comment by pvizeli** [comment]
I close this, because they have only an affect for 0.95. Please read my last tweet.
